"""initial_schema_multi_tenant

Revision ID: 0e240d0e27ec
Revises: 
Create Date: 2026-04-02 21:09:33.329871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e240d0e27ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magic_link_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('invite_code', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_link_tokens_email'), 'magic_link_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_magic_link_tokens_token'), 'magic_link_tokens', ['token'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_logout_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('coach_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_conversations_user_id'), 'coach_conversations', ['user_id'], unique=False)
    op.create_table('daily_health_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('sleep_duration_hours', sa.Float(), nullable=True),
    sa.Column('sleep_score', sa.Integer(), nullable=True),
    sa.Column('deep_min', sa.Integer(), nullable=True),
    sa.Column('rem_min', sa.Integer(), nullable=True),
    sa.Column('light_min', sa.Integer(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', 'source', name='uq_daily_health_user_date_source')
    )
    op.create_index(op.f('ix_daily_health_cache_date'), 'daily_health_cache', ['date'], unique=False)
    op.create_index(op.f('ix_daily_health_cache_user_id'), 'daily_health_cache', ['user_id'], unique=False)
    op.create_table('dexa_scans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('scan_date', sa.Date(), nullable=False),
    sa.Column('total_weight_lbs', sa.Float(), nullable=False),
    sa.Column('body_fat_pct', sa.Float(), nullable=False),
    sa.Column('fat_mass_lbs', sa.Float(), nullable=False),
    sa.Column('lean_mass_lbs', sa.Float(), nullable=False),
    sa.Column('bone_mass_lbs', sa.Float(), nullable=True),
    sa.Column('visceral_fat_lbs', sa.Float(), nullable=True),
    sa.Column('ag_ratio', sa.Float(), nullable=True),
    sa.Column('almi', sa.Float(), nullable=True),
    sa.Column('ffmi', sa.Float(), nullable=True),
    sa.Column('t_score', sa.Float(), nullable=True),
    sa.Column('facility', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_pdf_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dexa_scans_user_id'), 'dexa_scans', ['user_id'], unique=False)
    op.create_table('health_insights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('data_snapshot', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_insights_user_id'), 'health_insights', ['user_id'], unique=False)
    op.create_table('hevy_workouts',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('volume_lbs', sa.Float(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hevy_workouts_user_id'), 'hevy_workouts', ['user_id'], unique=False)
    op.create_table('invite_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('used_by', sa.UUID(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_codes_code'), 'invite_codes', ['code'], unique=True)
    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('plan_json', sa.Text(), nullable=False),
    sa.Column('calorie_target', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plans_user_id'), 'meal_plans', ['user_id'], unique=False)
    op.create_table('nutrition_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kcal', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_logs_date'), 'nutrition_logs', ['date'], unique=False)
    op.create_index(op.f('ix_nutrition_logs_user_id'), 'nutrition_logs', ['user_id'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('athlete_id', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'service', name='uq_oauth_tokens_user_service')
    )
    op.create_index(op.f('ix_oauth_tokens_user_id'), 'oauth_tokens', ['user_id'], unique=False)
    op.create_table('strava_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('moving_time_s', sa.Integer(), nullable=True),
    sa.Column('elapsed_time_s', sa.Integer(), nullable=True),
    sa.Column('total_elevation', sa.Float(), nullable=True),
    sa.Column('average_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('average_speed', sa.Float(), nullable=True),
    sa.Column('kudos_count', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strava_activities_user_id'), 'strava_activities', ['user_id'], unique=False)
    op.create_table('supplements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplements_user_id'), 'supplements', ['user_id'], unique=False)
    op.create_table('training_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('plan_json', sa.Text(), nullable=False),
    sa.Column('plan_markdown', sa.Text(), nullable=True),
    sa.Column('context_hash', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plans_user_id'), 'training_plans', ['user_id'], unique=False)
    op.create_table('user_consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consent_version', sa.String(length=20), nullable=False),
    sa.Column('consented_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_consents_user_id'), 'user_consents', ['user_id'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('height_inches', sa.Float(), nullable=True),
    sa.Column('bf_goal_pct', sa.Float(), nullable=True),
    sa.Column('vo2max_goal', sa.Float(), nullable=True),
    sa.Column('goal_date', sa.Date(), nullable=True),
    sa.Column('calorie_target', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('measurement_system', sa.String(length=10), nullable=True),
    sa.Column('training_device', sa.String(length=20), nullable=True),
    sa.Column('breakfast_pref', sa.Text(), nullable=True),
    sa.Column('lunch_pref', sa.Text(), nullable=True),
    sa.Column('dinner_pref', sa.Text(), nullable=True),
    sa.Column('mcp_api_key', sa.String(length=100), nullable=True),
    sa.Column('hevy_api_key', sa.String(length=100), nullable=True),
    sa.Column('training_days_strength', sa.Integer(), nullable=True),
    sa.Column('training_days_cardio', sa.Integer(), nullable=True),
    sa.Column('training_days_rest', sa.Integer(), nullable=True),
    sa.Column('training_days_mobility', sa.Integer(), nullable=True),
    sa.Column('preferred_exercises', sa.Text(), nullable=True),
    sa.Column('exercises_to_avoid', sa.Text(), nullable=True),
    sa.Column('dietary_preference', sa.String(length=30), nullable=True),
    sa.Column('preferred_cuisines', sa.Text(), nullable=True),
    sa.Column('weekly_email_enabled', sa.Boolean(), nullable=True),
    sa.Column('weekly_email_cc', sa.String(length=200), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=True),
    sa.Column('invite_code_used', sa.String(length=50), nullable=True),
    sa.Column('training_plan_recipients', sa.Text(), nullable=True),
    sa.Column('meal_plan_recipients', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_mcp_api_key'), 'user_profile', ['mcp_api_key'], unique=True)
    op.create_index(op.f('ix_user_profile_user_id'), 'user_profile', ['user_id'], unique=True)
    op.create_table('vo2max_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('vo2max', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vo2max_logs_user_id'), 'vo2max_logs', ['user_id'], unique=False)
    op.create_table('weekly_checkins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('training_adherence', sa.Integer(), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('diet_adherence', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start', name='uq_weekly_checkins_user_week')
    )
    op.create_index(op.f('ix_weekly_checkins_user_id'), 'weekly_checkins', ['user_id'], unique=False)
    op.create_index(op.f('ix_weekly_checkins_week_start'), 'weekly_checkins', ['week_start'], unique=False)
    op.create_table('weight_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_lbs', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_weight_logs_user_date')
    )
    op.create_index(op.f('ix_weight_logs_user_id'), 'weight_logs', ['user_id'], unique=False)
    op.create_table('hevy_exercise_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('workout_id', sa.String(length=100), nullable=False),
    sa.Column('exercise_name', sa.String(length=255), nullable=False),
    sa.Column('set_index', sa.Integer(), nullable=True),
    sa.Column('weight_lbs', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('set_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['hevy_workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hevy_exercise_sets_user_id'), 'hevy_exercise_sets', ['user_id'], unique=False)
    op.create_table('supplement_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('supplement_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplement_id'], ['supplements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplement_logs_date'), 'supplement_logs', ['date'], unique=False)
    op.create_index(op.f('ix_supplement_logs_user_id'), 'supplement_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplement_logs_user_id'), table_name='supplement_logs')
    op.drop_index(op.f('ix_supplement_logs_date'), table_name='supplement_logs')
    op.drop_table('supplement_logs')
    op.drop_index(op.f('ix_hevy_exercise_sets_user_id'), table_name='hevy_exercise_sets')
    op.drop_table('hevy_exercise_sets')
    op.drop_index(op.f('ix_weight_logs_user_id'), table_name='weight_logs')
    op.drop_table('weight_logs')
    op.drop_index(op.f('ix_weekly_checkins_week_start'), table_name='weekly_checkins')
    op.drop_index(op.f('ix_weekly_checkins_user_id'), table_name='weekly_checkins')
    op.drop_table('weekly_checkins')
    op.drop_index(op.f('ix_vo2max_logs_user_id'), table_name='vo2max_logs')
    op.drop_table('vo2max_logs')
    op.drop_index(op.f('ix_user_profile_user_id'), table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_mcp_api_key'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_user_consents_user_id'), table_name='user_consents')
    op.drop_table('user_consents')
    op.drop_index(op.f('ix_training_plans_user_id'), table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_index(op.f('ix_supplements_user_id'), table_name='supplements')
    op.drop_table('supplements')
    op.drop_index(op.f('ix_strava_activities_user_id'), table_name='strava_activities')
    op.drop_table('strava_activities')
    op.drop_index(op.f('ix_oauth_tokens_user_id'), table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_nutrition_logs_user_id'), table_name='nutrition_logs')
    op.drop_index(op.f('ix_nutrition_logs_date'), table_name='nutrition_logs')
    op.drop_table('nutrition_logs')
    op.drop_index(op.f('ix_meal_plans_user_id'), table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_invite_codes_code'), table_name='invite_codes')
    op.drop_table('invite_codes')
    op.drop_index(op.f('ix_hevy_workouts_user_id'), table_name='hevy_workouts')
    op.drop_table('hevy_workouts')
    op.drop_index(op.f('ix_health_insights_user_id'), table_name='health_insights')
    op.drop_table('health_insights')
    op.drop_index(op.f('ix_dexa_scans_user_id'), table_name='dexa_scans')
    op.drop_table('dexa_scans')
    op.drop_index(op.f('ix_daily_health_cache_user_id'), table_name='daily_health_cache')
    op.drop_index(op.f('ix_daily_health_cache_date'), table_name='daily_health_cache')
    op.drop_table('daily_health_cache')
    op.drop_index(op.f('ix_coach_conversations_user_id'), table_name='coach_conversations')
    op.drop_table('coach_conversations')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_magic_link_tokens_token'), table_name='magic_link_tokens')
    op.drop_index(op.f('ix_magic_link_tokens_email'), table_name='magic_link_tokens')
    op.drop_table('magic_link_tokens')
    # ### end Alembic commands ###
