"""add_telegram_fields_to_user_profile

Revision ID: 4a3252a537f4
Revises: e1f2a3b4c5d6
Create Date: 2026-04-05 12:58:52.432389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3252a537f4'
down_revision: Union[str, None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True))
    op.add_column('user_profile', sa.Column('telegram_username', sa.String(length=100), nullable=True))
    op.add_column('user_profile', sa.Column('telegram_connected_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_profile_telegram_chat_id'), 'user_profile', ['telegram_chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_telegram_chat_id'), table_name='user_profile')
    op.drop_column('user_profile', 'telegram_connected_at')
    op.drop_column('user_profile', 'telegram_username')
    op.drop_column('user_profile', 'telegram_chat_id')
    # ### end Alembic commands ###
